# Generated by Django 4.2.5 on 2024-07-13 18:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer_service", "0003_alter_servicerequest_resolved_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customeraccount",
            name="address",
        ),
        migrations.RemoveField(
            model_name="customeraccount",
            name="phone_number",
        ),
    ]
